Repository google/mobly, pull requests merged in 2018-02, with the labels that each got.

#399 Adding None checks to stop_standing_subprocess
  mobly/utils.py
  tests/mobly/utils_test.py
Labels: bug

#389 Allow logging to start before running tests
  mobly/test_runner.py
  tests/mobly/output_test.py
  tests/mobly/test_runner_test.py
Labels: improvement

#401 Fix 80 char line lengths in TestRunner._teardown_logger().
  mobly/test_runner.py
  tests/mobly/test_runner_test.py
Labels: refactor

#400 Fix Windows Android M empty line issue with instrumentation parser
  mobly/base_instrumentation_test.py
  tests/mobly/base_instrumentation_test_test.py
Labels: improvement

#408 Handle calling `asserts.abort_all` in `on_fail`
  mobly/base_test.py
  tests/lib/integration3_test.py
  tests/mobly/base_test_test.py
  tests/mobly/test_runner_test.py
Labels: bug
