Repository google/mobly, pull requests merged in 2018-05, with the labels that each got.

#443 Fix adb.forward
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: bug

#444 Extend runtime test info for `setup_class` stage.
  mobly/base_test.py
  mobly/runtime_test_info.py
  tests/mobly/base_test_test.py
Labels: improvement

#445 Sphinx doc fixes.
  docs/mobly.rst
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/adb.py
  mobly/suite_runner.py
  tests/mobly/suite_runner_test.py
Labels: bug, docs

#426 Add windows build badge
  README.md
Labels: testing

#448 Add pytest_cache to .gitignore
  .gitignore
Labels: improvement

#392 Implemented streamed instrumentation tests
  mobly/base_instrumentation_test.py
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/base_instrumentation_test_test.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: improvement

#451 Apply cleanups suggested by PyFlakes.
  mobly/base_instrumentation_test.py
  mobly/base_test.py
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
  mobly/controllers/android_device_lib/sl4a_client.py
  mobly/controllers/android_device_lib/snippet_client.py
  mobly/expects.py
  mobly/records.py
  mobly/signals.py
  mobly/suite_runner.py
Labels: refactor

#450 Mobly release 1.7.3.
  CHANGELOG.md
  setup.py
Labels: release
