Repository google/mobly, pull requests merged in 2018-08, with the labels that each got.

#487 Fix max timeout for `CallbackHandler.waitForEvent`.
  mobly/controllers/android_device_lib/callback_handler.py
  tests/mobly/controllers/android_device_lib/callback_handler_test.py
Labels: bug

#489 Clean up dep requirements in `setup.py`.
  setup.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
Labels: refactor, testing

#490 Mobly Release 1.7.5
  CHANGELOG.md
  setup.py
Labels: release

#493 Move `register_controller` into `base_test`.
  mobly/base_test.py
  mobly/config_parser.py
  mobly/records.py
  mobly/test_runner.py
  tests/mobly/base_test_test.py
  tests/mobly/test_runner_test.py
  tests/mobly/test_suite_test.py
Labels: refactor
