Repository google/mobly, pull requests merged in 2018-06, with the labels that each got.

#455 Fix error argument formatting which was leading to not callable TypeE…
  mobly/controllers/android_device_lib/snippet_client.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
Labels: bug

#453 Log command for _execute_and_process_stdout.
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: improvement

#456 Fix _execute_and_process_stdout.
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: bug

#458 Fix psutil unit test flake in Windows CI environment
  setup.py
Labels: bug

#460 Fix unicode encoding issues with records module.
  mobly/records.py
  tests/mobly/records_test.py
Labels: bug

#463 Add an API to unload a single snippet.
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: new feature

#464 Add unit test for `on_fail` and `setup_class` both raising errors.
  mobly/base_test.py
  tests/mobly/base_test_test.py
Labels: bug, testing

#465 Use io.open to set file encoding
  mobly/config_parser.py
  mobly/controllers/android_device.py
  mobly/controllers/iperf_server.py
  mobly/controllers/monsoon.py
  mobly/records.py
  mobly/utils.py
  tests/mobly/base_test_test.py
  tests/mobly/config_parser_test.py
  tests/mobly/controllers/android_device_test.py
  tests/mobly/output_test.py
  tests/mobly/records_test.py
  tests/mobly/test_runner_test.py
  tests/mobly/utils_test.py
Labels: improvement
