Repository google/mobly, pull requests merged in 2018-03, with the labels that each got.

#415 Fix comment over 80 characters.
  mobly/controllers/android_device.py
Labels: refactor

#416 Fix key value unpacking issue.
  mobly/base_instrumentation_test.py
  tests/mobly/base_instrumentation_test_test.py
Labels: bug

#417 Make `SnippetEvent` loggable.
  mobly/controllers/android_device_lib/snippet_event.py
  setup.py
  tests/mobly/controllers/android_device_lib/snippet_event_test.py
Labels: improvement

#418 Remove the usage of `testfixtures`.
  setup.py
  tests/mobly/controllers/android_device_lib/snippet_event_test.py
Labels: testing
