Repository google/mobly, pull requests merged in 2018-04, with the labels that each got.

#413 Fixed missing stacktrace for py2 for setup_test failure
  mobly/base_test.py
  tests/mobly/base_test_test.py
Labels: bug

#419 Fix exception raising in `AndroidDevice.load_snippet`.
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/snippet_client.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
  tests/mobly/controllers/android_device_test.py
Labels: bug

#376 APIs to add additional blocks in test summary file
  mobly/base_test.py
  mobly/records.py
  tests/mobly/base_test_test.py
  tests/mobly/records_test.py
Labels: new feature

#428 Mobly Release 1.7.2.
  CHANGELOG.md
  setup.py
Labels: release

#430 Fix instrumentation decode issue with python3.
  mobly/base_instrumentation_test.py
  tests/mobly/base_instrumentation_test_test.py
Labels: bug

#433 Fix cat_adb_log on Windows.
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
  tests/mobly/logger_test.py
Labels: bug

#427 Disable the blacklist on hidden apis for sl4a/snippets
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
  mobly/controllers/android_device_lib/sl4a_client.py
  mobly/controllers/android_device_lib/snippet_client.py
  tests/mobly/controllers/android_device_lib/sl4a_client_test.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
Labels: improvement

#425 Fix unit tests on Windows.
  tests/mobly/controllers/monsoon_test.py
  tests/mobly/output_test.py
  tests/mobly/test_runner_test.py
Labels: testing

#432 Fix instrumentation output on python3.
  mobly/base_instrumentation_test.py
  tests/mobly/base_instrumentation_test_test.py
Labels: bug

#439 Change UserData timestamp from a float to an int
  mobly/base_test.py
Labels: improvement

#437 Add an option to get the stderr of an adb command.
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: improvement
