Repository google/mobly, pull requests merged in 2018-07, with the labels that each got.

#467 Support alias for test classes when using suite.
  mobly/base_test.py
  mobly/config_parser.py
  mobly/test_runner.py
  tests/mobly/test_runner_test.py
Labels: new feature

#468 Replace android.support references with androidx
  mobly/base_instrumentation_test.py
  tests/mobly/base_instrumentation_test_test.py
Labels: refactor

#471 Use `ro.debuggable` to decide if a device is rootable.
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement

#473 Log each rpc msg in snippet client for better debugging.
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
Labels: improvement

#472 Log test config at the beginning of the test run.
  mobly/config_parser.py
  mobly/test_runner.py
  tests/mobly/config_parser_test.py
Labels: improvement

#478 Improve boundary clarity of execution stages in logs
  mobly/base_test.py
  tests/mobly/base_test_test.py
Labels: bug, improvement

#475 Normalize serial for log name
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement

#481 Mobly Release 1.7.4.
  CHANGELOG.md
  setup.py
Labels: release

#483 [Unit test] Verify controller objects do not persist across classes
  tests/mobly/test_suite_test.py
Labels: testing
