Repository google/mobly, pull requests merged in 2018-10, with the labels that each got.

#513 Fix pause/resume behavior for snippet management service.
  mobly/controllers/android_device_lib/service_manager.py
  mobly/controllers/android_device_lib/services/snippet_management_service.py
  mobly/controllers/android_device_lib/snippet_client.py
  tests/mobly/controllers/android_device_lib/service_manager_test.py
  tests/mobly/controllers/android_device_lib/services/snippet_management_service_test.py
Labels: bug

#511 Package sl4a client management into a service.
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
  mobly/controllers/android_device_lib/service_manager.py
  mobly/controllers/android_device_lib/services/sl4a_service.py
  mobly/controllers/android_device_lib/sl4a_client.py
  mobly/controllers/android_device_lib/snippet_client.py
  tests/mobly/controllers/android_device_lib/service_manager_test.py
  tests/mobly/controllers/android_device_lib/services/sl4a_service_test.py
  tools/sl4a_shell.py
Labels: bug, improvement, refactor

#517 Remove unused args in logger module.
  mobly/logger.py
  tests/mobly/output_test.py
Labels: bug

#516 Fix a typo in docstring.
  mobly/controllers/android_device.py
Labels: docs

#518 Remove unused arg from stop_standing_subprocess.
  mobly/utils.py
Labels: bug

#520 Fix wrong asserts in some python tests.
  tests/mobly/base_instrumentation_test_test.py
  tests/mobly/output_test.py
Labels: bug, testing

#521 Fix pytest init warnings.
  setup.cfg
  tests/lib/mock_instrumentation_test.py
  tests/mobly/base_instrumentation_test_test.py
  tests/mobly/base_test_test.py
Labels: bug

#522 Fix load_sl4a.
  mobly/controllers/android_device_lib/services/sl4a_service.py
  tests/mobly/controllers/android_device_lib/services/sl4a_service_test.py
  tests/mobly/controllers/android_device_test.py
Labels: bug

#524 Fix pytest warning when run via setup.py test
  setup.py
Labels: testing

#515 Simplify service interface and post-service clean ups.
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/jsonrpc_shell_base.py
  mobly/controllers/android_device_lib/service_manager.py
  mobly/controllers/android_device_lib/services/base_service.py
  mobly/controllers/android_device_lib/services/logcat.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement, refactor

#525 Introduce a helper method for creating per-test logcat excerpts.
  mobly/controllers/android_device_lib/services/logcat.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
Labels: new feature

#527 Add a quick tutorial for services.
  README.md
  docs/android_device_service.md
  docs/tutorial.md
Labels: docs

#530 Add ability to specify a custom env for start_standing_subprocess
  mobly/utils.py
  tests/mobly/utils_test.py
Labels: improvement

#532 Add serial attr in `AdbError`.
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: improvement

#534 Add serial to adb timeout error.
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: improvement

#531 Fix `expects` for different test stages.
  mobly/base_test.py
  tests/mobly/base_test_test.py
Labels: bug

#535 Mobly release 1.8
  CHANGELOG.md
  setup.py
Labels: release

#536 Fix sphinx docs.
  docs/conf.py
  docs/mobly.controllers.android_device_lib.rst
  docs/mobly.controllers.android_device_lib.services.rst
  docs/mobly.rst
Labels: docs

#537 Docstring fixes for sphinx warnings.
  mobly/base_test.py
  mobly/controllers/android_device_lib/callback_handler.py
Labels: docs

#538 Introduce a proper execution stage for final clean up.
  mobly/base_test.py
  mobly/controller_manager.py
  tests/mobly/base_test_test.py
  tests/mobly/controller_manager_test.py
Labels: bug, improvement

#539 Fix a unit test.
  tests/mobly/controller_manager_test.py
Labels: testing

#540 Fix unit test flake.
  mobly/controller_manager.py
  tests/mobly/controller_manager_test.py
Labels: testing

#541 Fix method docs in service_manager
  mobly/controllers/android_device_lib/service_manager.py
Labels: docs
