Repository google/mobly, pull requests merged in 2018-09, with the labels that each got.

#495 Properly record controller info.
  mobly/base_test.py
  mobly/records.py
  mobly/test_runner.py
  tests/lib/mock_second_controller.py
  tests/mobly/base_test_test.py
  tests/mobly/records_test.py
  tests/mobly/test_runner_test.py
Labels: improvement, refactor

#496 Fix a potential racing condition in unit test.
  tests/mobly/base_test_test.py
  tests/mobly/test_runner_test.py
Labels: testing

#497 Create a proper manager for controllers.
  mobly/base_test.py
  mobly/controller_manager.py
  mobly/records.py
  tests/mobly/base_test_test.py
  tests/mobly/controller_manager_test.py
  tests/mobly/records_test.py
Labels: improvement, refactor

#499 Add controller configs attr back
  mobly/base_test.py
  mobly/controller_manager.py
Labels: improvement

#503 Introduce proper service management for AndroidDevice.
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/errors.py
  mobly/controllers/android_device_lib/service_manager.py
  mobly/controllers/android_device_lib/services/__init__.py
  mobly/controllers/android_device_lib/services/base_service.py
  mobly/controllers/android_device_lib/services/logcat.py
  tests/mobly/controllers/android_device_lib/errors_test.py
  tests/mobly/controllers/android_device_lib/service_manager_test.py
  tests/mobly/controllers/android_device_lib/services/__init__.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement, new feature, refactor

#506 Put back the "adb logcat -c" workaround for Android O
  mobly/controllers/android_device_lib/services/logcat.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
Labels: bug

#510 Delete sentence fragment in `test_runner.py`
  mobly/test_runner.py
Labels: refactor

#507 Apply service mechanism for snippet client management.
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/service_manager.py
  mobly/controllers/android_device_lib/services/snippet_management_service.py
  mobly/controllers/android_device_lib/snippet_client.py
  tests/mobly/controllers/android_device_lib/services/snippet_management_service_test.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
  tests/mobly/controllers/android_device_test.py
Labels: bug, improvement, refactor
