Repository google/mobly, pull requests merged in 2019-08, with the labels that each got.

#584 Add ability to override the log alias directory.
  mobly/logger.py
  mobly/test_runner.py
  tests/mobly/logger_test.py
  tests/mobly/output_test.py
Labels: improvement

#612 Set default logging values for test runner.
  mobly/test_runner.py
  tests/mobly/test_runner_test.py
Labels: bug

#616 Remove context behavior of `base_test`
  mobly/base_test.py
  mobly/test_runner.py
Labels: refactor

#617 Mobly Release 1.9.
  CHANGELOG.md
  setup.py
Labels: release

#620 Add back rst files for sphinx.
  docs/mobly.controllers.android_device_lib.rst
  docs/mobly.controllers.android_device_lib.services.rst
  docs/mobly.controllers.attenuator_lib.rst
  docs/mobly.controllers.rst
  docs/mobly.controllers.sniffer_lib.local.rst
  docs/mobly.controllers.sniffer_lib.rst
  docs/mobly.rst
Labels: docs

#621 Update sphinx config
  .readthedocs.yml
  docs/requirements.txt
  docs/rtd_requirements.txt
Labels: docs

#622 Mobly Release 1.9.1.
  CHANGELOG.md
  setup.py
Labels: release

#624 Add context on the ordering of `root_adb` commands.
  mobly/controllers/android_device.py
Labels: docs
