Repository google/mobly, pull requests merged in 2019-05, with the labels that each got.

#576 Make take bug report move convenient to use.
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement

#578 Fix yaml load usage warnings.
  mobly/config_parser.py
  tests/mobly/base_test_test.py
  tests/mobly/output_test.py
  tests/mobly/records_test.py
  tests/mobly/test_runner_test.py
Labels: testing

#577 Add an API for getting adb prop in batch.
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/adb.py
  tests/lib/mock_android_device.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: improvement

#580 Handle malformatted adb getprop output.
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: bug

#581 Handle \r\n newlines.
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: bug
