Repository google/mobly, pull requests merged in 2019-09, with the labels that each got.

#626 Add is emulator property
  mobly/controllers/android_device.py
  tests/lib/mock_android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement

#628 Fix adb instrument output.
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: bug

#629 Add logic to sanitize windows filenames
  mobly/controllers/android_device.py
  mobly/logger.py
  tests/mobly/logger_test.py
Labels: improvement

#630 Add a standard method for generating output filenames in `AndroidDevice`.
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: new feature

#631 Add find_subclasses_in_module utility method.
  mobly/test_runner.py
  mobly/utils.py
  tests/lib/multiple_subclasses_module.py
  tests/mobly/utils_test.py
Labels: new feature, refactor

#632 Add find_subclass_in_module utility.
  mobly/test_runner.py
  mobly/utils.py
  tests/mobly/test_runner_test.py
  tests/mobly/utils_test.py
Labels: bug

#633 Standardize output excerpt APIs in services.
  mobly/controllers/android_device_lib/service_manager.py
  mobly/controllers/android_device_lib/services/base_service.py
  mobly/controllers/android_device_lib/services/logcat.py
  tests/mobly/controllers/android_device_lib/service_manager_test.py
  tests/mobly/controllers/android_device_lib/services/base_service_test.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
Labels: improvement, new feature, refactor

#634 Utilize new output file APIs in `logcat_service`.
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/services/logcat.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement, refactor
