Repository google/mobly, pull requests merged in 2019-07, with the labels that each got.

#590 Fix windows cbuild pytest pytype error
  setup.py
Labels: bug

#588 Add mixin for instrumentation test.
  mobly/base_instrumentation_test.py
Labels: improvement

#591 Fix service manager error handling.
  mobly/controllers/android_device_lib/service_manager.py
  mobly/expects.py
  tests/mobly/controllers/android_device_lib/service_manager_test.py
Labels: bug

#594 Update and rename CONTRIBUTING to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs

#595 Fix typos.
  mobly/base_instrumentation_test.py
  mobly/base_test.py
  mobly/controllers/monsoon.py
  mobly/signals.py
  mobly/utils.py
  tests/mobly/base_test_test.py
  tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
  tests/mobly/logger_test.py
Labels: improvement

#596 A pull request to solve the "AdbTimeoutError: Timed out executing command "adb -s d6d5974 shell getprop sys.boot_completed" after 5s. " bug during waiting the device for fully boot up as adb.
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: bug

#598 Deduplicated the mock adb proxy.
  tests/lib/mock_android_device.py
  tests/mobly/controllers/android_device_lib/sl4a_client_test.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
Labels: refactor, testing

#597 Add retries for adb getprops.
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: bug

#599 Extend build info
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
  tests/lib/mock_android_device.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
  tests/mobly/controllers/android_device_lib/sl4a_client_test.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement

#601 Workaround socket library import issue.
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
Labels: bug

#600 Cache build info
  mobly/controllers/android_device.py
  tests/lib/mock_android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement

#603 New yapf formatting.
  mobly/asserts.py
  mobly/base_instrumentation_test.py
  mobly/config_parser.py
  mobly/controller_manager.py
  mobly/controllers/__init__.py
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/__init__.py
  mobly/controllers/android_device_lib/adb.py
  mobly/controllers/android_device_lib/callback_handler.py
  mobly/controllers/android_device_lib/event_dispatcher.py
  mobly/controllers/android_device_lib/fastboot.py
  mobly/controllers/android_device_lib/service_manager.py
  mobly/controllers/android_device_lib/services/logcat.py
  mobly/controllers/android_device_lib/services/sl4a_service.py
  mobly/controllers/android_device_lib/sl4a_client.py
  mobly/controllers/android_device_lib/snippet_client.py
  mobly/controllers/android_device_lib/snippet_event.py
  mobly/controllers/attenuator.py
  mobly/controllers/attenuator_lib/minicircuits.py
  mobly/controllers/attenuator_lib/telnet_scpi_client.py
  mobly/controllers/monsoon.py
  mobly/controllers/sniffer.py
  mobly/controllers/sniffer_lib/__init__.py
  mobly/controllers/sniffer_lib/local/__init__.py
  mobly/controllers/sniffer_lib/local/local_base.py
  mobly/controllers/sniffer_lib/local/tcpdump.py
  mobly/controllers/sniffer_lib/local/tshark.py
  mobly/records.py
  mobly/suite_runner.py
  mobly/test_runner.py
  mobly/utils.py
  tests/mobly/controllers/android_device_test.py
Labels: refactor

#602 Make `take_bug_reports` consistent with its singular version.
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement

#604 Remove an extra param.
  mobly/controllers/sniffer_lib/local/local_base.py
Labels: bug

#607 Guarantee service start/stop order in AndroidDevice.
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/service_manager.py
  tests/mobly/controllers/android_device_lib/service_manager_test.py
  tests/mobly/controllers/android_device_test.py
Labels: bug, improvement

#609 Make state explicit in logcat service update config.
  mobly/controllers/android_device_lib/services/logcat.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
Labels: improvement

#606 Make test_runner logging a context manager.
  mobly/test_runner.py
  tests/mobly/output_test.py
  tests/mobly/test_runner_test.py
  tests/mobly/test_suite_test.py
Labels: improvement

#610 Fix suite_runner with logger.
  mobly/suite_runner.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
  tests/mobly/suite_runner_test.py
Labels: bug

#611 Fix typo.
  mobly/test_runner.py
  tests/mobly/test_runner_test.py
Labels: bug
