Repository google/mobly, pull requests merged in 2019-12, with the labels that each got.

#659 Removes unnecessary list handling from -c flag.
  mobly/suite_runner.py
  mobly/test_runner.py
Labels: refactor

#658 Rewrite logcat's create_output_excerpts to avoid dangling excerpts.
  mobly/controllers/android_device_lib/services/logcat.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement, refactor

#657 Change MISMATCHED_API_ID from 'Mismatched API id.' to 'RPC request-re…
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
Labels: docs

#661 Improve concurrent_exec util
  mobly/utils.py
  tests/mobly/utils_test.py
Labels: improvement
