Repository google/mobly, pull requests merged in 2019-10, with the labels that each got.

#636 Preserve extensions when truncating filenames
  mobly/logger.py
  tests/mobly/logger_test.py
Labels: bug, improvement

#637 Fix line length on comment
  mobly/logger.py
Labels: docs

#635 Standardize filenames for logcat and bugreport.
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/services/logcat.py
  tests/lib/mock_android_device.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement, refactor

#638 Fix take_bug_report int issue.
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: bug

#640 Remove long deprecated APIs.
  mobly/base_test.py
  mobly/controllers/android_device.py
  mobly/logger.py
  tests/mobly/base_test_test.py
Labels: refactor

#641 Rename test_bed_name to testbed_name.
  mobly/base_test.py
  mobly/config_parser.py
  mobly/suite_runner.py
  mobly/test_runner.py
  tests/mobly/output_test.py
  tests/mobly/test_runner_test.py
  tests/mobly/test_suite_test.py
Labels: refactor

#643 Re-include test_bed_name in load_test_config_file() for backward comp…
  mobly/config_parser.py
Labels: refactor

#639 Guarantees the test stage end message is always logged.
  mobly/base_test.py
  tests/mobly/base_test_test.py
Labels: bug

#644 Allow overriding props with setters via config in `AndroidDevice`.
  mobly/controllers/android_device.py
  mobly/utils.py
  tests/mobly/controllers/android_device_test.py
  tests/mobly/utils_test.py
Labels: improvement

#645 [adb] Add a util to retrieve the current user ID.
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: new feature

#646 Correct docstring for `current_user_id`
  mobly/controllers/android_device_lib/adb.py
Labels: docs

#647 Always operate on the current user in `snippet_client`.
  mobly/controllers/android_device_lib/snippet_client.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
Labels: improvement

#648 Change test case filter to use callable() instead of inspect.ismethod()
  mobly/base_test.py
  tests/mobly/base_test_test.py
Labels: improvement

#650 Log path changes in `BaseTestClass`.
  mobly/base_test.py
  mobly/logger.py
  mobly/test_runner.py
  tests/mobly/base_test_test.py
  tests/mobly/output_test.py
  tests/mobly/test_runner_test.py
Labels: new feature

#652 Updated formatting of config_parser_test.py
  tests/mobly/config_parser_test.py
Labels: refactor

#654 Defaults the controller and user_params to empty dictionaries in TestRunConfig.
  mobly/config_parser.py
  tests/mobly/config_parser_test.py
Labels: improvement

#653 Do not add `--user` in snippet commands for SDK < 24.
  mobly/controllers/android_device_lib/snippet_client.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
Labels: improvement
