Repository google/mobly, pull requests merged in 2019-03, with the labels that each got.

#564 Remove `tests` module from installation.
  setup.py
Labels: release

#567 Add a note on dropping py2 support.
  README.md
Labels: docs

#568 Remove unused code path.
  mobly/base_test.py
Labels: refactor

#565 Fix assert message to have a single stacktrace
  mobly/asserts.py
Labels: bug

#571 Add support for specifying UID for test cases
  mobly/base_test.py
  mobly/records.py
  tests/mobly/base_test_test.py
  tests/mobly/records_test.py
Labels: improvement, new feature

#570 Moving the util and updating references in tests
  mobly/controllers/android_device_lib/adb.py
  mobly/utils.py
  tests/mobly/controllers/android_device_lib/adb_test.py
  tests/mobly/utils_test.py
Labels: refactor

#572 Remove deprecated service-related APIs
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: refactor

#573 Remove `ad.stop_services` for good.
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: refactor

#574 Add logic for ANDROID_SERIAL to snippet shell.
  mobly/controllers/android_device_lib/jsonrpc_shell_base.py
  tests/mobly/controllers/android_device_lib/jsonrpc_shell_base_test.py
Labels: improvement

#575 Expose `cwd` in subprocess util.
  mobly/utils.py
  tests/mobly/utils_test.py
Labels: improvement
