Repository google/mobly, pull requests merged in 2019-02, with the labels that each got.

#555 Fix Python3 str handling error.
  mobly/controllers/android_device_lib/services/logcat.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
Labels: bug, customer issue

#557 Correct docstring of ad.reboot.
  mobly/controllers/android_device.py
Labels: docs

#558 Fix deadlock issue with adb commands with timeout.
  mobly/controllers/android_device_lib/adb.py
  mobly/utils.py
  tests/mobly/controllers/android_device_lib/adb_test.py
  tests/mobly/utils_test.py
Labels: bug, customer issue

#556 Add a default timeout for adb getprop calls.
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: improvement

#562 Fix a typo in getprop.
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: bug

#563 Fix flaky timeout test on Windows.
  tests/mobly/utils_test.py
Labels: improvement
