Repository google/mobly, pull requests merged in 2020-10, with the labels that each got.

#681 Add not None check in Logcat.create_output_excerpts.
  mobly/controllers/android_device_lib/services/logcat.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
Labels: bug

#683 Sets default not to do verbose logging
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
  tests/lib/jsonrpc_client_test_base.py
  tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py
Labels: new feature

#686 Reduce unused variable in _client_receive.
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
  tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py
Labels: refactor
