Repository google/mobly, pull requests merged in 2021-01, with the labels that each got.

#688 Fix a potential resource leakage in `_print_test_names`.
  mobly/test_runner.py
  tests/mobly/test_runner_test.py
Labels: bug

#692 Mobly Release 1.10.1.
  CHANGELOG.md
  setup.py
Labels: release

#679 Drop Python 2 compatibility
  .travis.yml
  mobly/asserts.py
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/adb.py
  mobly/controllers/monsoon.py
  mobly/utils.py
Labels: refactor

#693 Remove deprecated code.
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
  mobly/controllers/android_device_lib/services/logcat.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
Labels: refactor

#690 Add a retry mechanism for the ADB command "root"
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: improvement

#695 Drop py2 support in setup.py test
  setup.py
Labels: refactor

#701 Move to 2-space indent: top-level mobly files
  mobly/asserts.py
  mobly/base_instrumentation_test.py
  mobly/base_test.py
  mobly/config_parser.py
  mobly/controller_manager.py
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
  mobly/controllers/android_device_lib/services/logcat.py
  mobly/expects.py
  mobly/keys.py
  mobly/logger.py
  mobly/records.py
  mobly/runtime_test_info.py
  mobly/signals.py
  mobly/suite_runner.py
  mobly/test_runner.py
  mobly/utils.py
  setup.py
Labels: refactor

#703 Drop py2 and py<3.6 support in README.md.
  README.md
Labels: docs

#702 Add tox config for running unit tests.
  .gitignore
  README.md
  tox.ini
Labels: testing

#705 Move to 2-space indent: AndroidDevice related files
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/adb.py
  mobly/controllers/android_device_lib/callback_handler.py
  mobly/controllers/android_device_lib/errors.py
  mobly/controllers/android_device_lib/event_dispatcher.py
  mobly/controllers/android_device_lib/fastboot.py
  mobly/controllers/android_device_lib/jsonrpc_shell_base.py
  mobly/controllers/android_device_lib/service_manager.py
  mobly/controllers/android_device_lib/services/base_service.py
  mobly/controllers/android_device_lib/services/sl4a_service.py
  mobly/controllers/android_device_lib/services/snippet_management_service.py
  mobly/controllers/android_device_lib/sl4a_client.py
  mobly/controllers/android_device_lib/snippet_client.py
  mobly/controllers/android_device_lib/snippet_event.py
Labels: refactor

#704 Make a logging statement more contextual.
  mobly/base_test.py
Labels: improvement

#708 Fix a non-pythonic usage of `not`.
  mobly/controllers/android_device_lib/event_dispatcher.py
Labels: improvement

#706 Fix some wordings in README.md.
  README.md
Labels: docs

#711 Move to 2-space indent: tools
  tools/sl4a_shell.py
  tools/snippet_shell.py
Labels: refactor

#710 Move to 2-space indent: test files except AndroidDevice related
  tests/mobly/asserts_test.py
  tests/mobly/base_instrumentation_test_test.py
  tests/mobly/base_test_test.py
  tests/mobly/config_parser_test.py
  tests/mobly/controller_manager_test.py
  tests/mobly/controllers/android_device_test.py
  tests/mobly/controllers/monsoon_test.py
  tests/mobly/logger_test.py
  tests/mobly/output_test.py
  tests/mobly/records_test.py
  tests/mobly/suite_runner_test.py
  tests/mobly/test_runner_test.py
  tests/mobly/test_suite_test.py
  tests/mobly/utils_test.py
Labels: refactor

#709 Move to 2-space indent: AndroidDevice related test files.
  tests/mobly/controllers/android_device_lib/adb_test.py
  tests/mobly/controllers/android_device_lib/callback_handler_test.py
  tests/mobly/controllers/android_device_lib/errors_test.py
  tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py
  tests/mobly/controllers/android_device_lib/jsonrpc_shell_base_test.py
  tests/mobly/controllers/android_device_lib/service_manager_test.py
  tests/mobly/controllers/android_device_lib/services/base_service_test.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
  tests/mobly/controllers/android_device_lib/services/sl4a_service_test.py
  tests/mobly/controllers/android_device_lib/services/snippet_management_service_test.py
  tests/mobly/controllers/android_device_lib/sl4a_client_test.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
  tests/mobly/controllers/android_device_lib/snippet_event_test.py
Labels: refactor

#707 Move to 2-space indent: tests/lib/*.py.
  tests/lib/integration2_test.py
  tests/lib/integration3_test.py
  tests/lib/integration_test.py
  tests/lib/jsonrpc_client_test_base.py
  tests/lib/mock_android_device.py
  tests/lib/mock_controller.py
  tests/lib/mock_instrumentation_test.py
  tests/lib/mock_second_controller.py
  tests/lib/multiple_subclasses_module.py
  tests/lib/teardown_class_failure_test.py
  tests/lib/utils.py
Labels: refactor

#714 Fix some usages of asserts in tests.
  tests/mobly/base_test_test.py
  tests/mobly/records_test.py
Labels: testing
