Repository google/mobly, pull requests merged in 2021-02, with the labels that each got.

#715 Remove some py2 workarounds.
  mobly/controllers/android_device_lib/services/base_service.py
  mobly/records.py
  tests/lib/jsonrpc_client_test_base.py
  tests/mobly/controllers/android_device_test.py
Labels: refactor

#716 Remove more py2 workarounds.
  mobly/records.py
  mobly/utils.py
  tests/mobly/base_instrumentation_test_test.py
  tests/mobly/controllers/android_device_lib/service_manager_test.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
Labels: refactor

#718 Minor fixes for jsonrpc client.
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
  mobly/controllers/android_device_lib/services/base_service.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
Labels: refactor, testing

#717 Improve port picking logic.
  mobly/controllers/android_device_lib/adb.py
  mobly/utils.py
  tests/mobly/controllers/android_device_lib/adb_test.py
  tests/mobly/utils_test.py
Labels: improvement

#721 Remove importing class from modules.
  mobly/controllers/android_device_lib/event_dispatcher.py
Labels: refactor

#722 Drop the py2 compatibility in super() statements.
  mobly/controllers/android_device_lib/errors.py
  mobly/controllers/android_device_lib/services/logcat.py
  mobly/controllers/android_device_lib/services/snippet_management_service.py
  mobly/controllers/android_device_lib/sl4a_client.py
  mobly/controllers/android_device_lib/snippet_client.py
  mobly/signals.py
  tests/lib/mock_instrumentation_test.py
  tests/mobly/base_test_test.py
  tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py
Labels: refactor

#719 Make quote delimiter consistent in mobly/utils.py.
  mobly/utils.py
Labels: refactor

#720 Drop the py2 compatibility support modules.
  mobly/controllers/android_device_lib/jsonrpc_shell_base.py
  mobly/controllers/android_device_lib/snippet_client.py
  mobly/logger.py
  mobly/test_runner.py
  tools/snippet_shell.py
Labels: refactor

#723 Run tox instead setup.py test with Travis-CI.
  .travis.yml
Labels: testing

#727 Drop the py2 compatibility in raise_with_traceback.
  mobly/base_test.py
Labels: refactor

#726 Drop the py2 compatibility in unittest usages.
  tests/mobly/asserts_test.py
  tests/mobly/base_instrumentation_test_test.py
  tests/mobly/base_test_test.py
  tests/mobly/controller_manager_test.py
  tests/mobly/controllers/android_device_lib/adb_test.py
  tests/mobly/controllers/android_device_lib/callback_handler_test.py
  tests/mobly/controllers/android_device_lib/errors_test.py
  tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py
  tests/mobly/controllers/android_device_lib/jsonrpc_shell_base_test.py
  tests/mobly/controllers/android_device_lib/service_manager_test.py
  tests/mobly/controllers/android_device_lib/services/base_service_test.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
  tests/mobly/controllers/android_device_lib/services/sl4a_service_test.py
  tests/mobly/controllers/android_device_lib/services/snippet_management_service_test.py
  tests/mobly/controllers/android_device_lib/sl4a_client_test.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
  tests/mobly/controllers/android_device_lib/snippet_event_test.py
  tests/mobly/controllers/android_device_test.py
  tests/mobly/controllers/monsoon_test.py
  tests/mobly/records_test.py
  tests/mobly/test_runner_test.py
  tests/mobly/test_suite_test.py
  tests/mobly/utils_test.py
Labels: refactor

#724 Drop the py2 compatibility in class declaration statements.
  docs/android_device_service.md
  mobly/asserts.py
  mobly/base_instrumentation_test.py
  mobly/base_test.py
  mobly/config_parser.py
  mobly/controller_manager.py
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/adb.py
  mobly/controllers/android_device_lib/callback_handler.py
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
  mobly/controllers/android_device_lib/jsonrpc_shell_base.py
  mobly/controllers/android_device_lib/service_manager.py
  mobly/controllers/android_device_lib/services/logcat.py
  mobly/controllers/android_device_lib/snippet_event.py
  mobly/controllers/attenuator.py
  mobly/controllers/attenuator_lib/minicircuits.py
  mobly/controllers/attenuator_lib/telnet_scpi_client.py
  mobly/controllers/iperf_server.py
  mobly/controllers/monsoon.py
  mobly/controllers/sniffer.py
  mobly/expects.py
  mobly/records.py
  mobly/runtime_test_info.py
  mobly/test_runner.py
  tests/lib/jsonrpc_client_test_base.py
  tests/lib/mock_android_device.py
  tests/lib/mock_controller.py
  tests/lib/mock_second_controller.py
  tests/lib/multiple_subclasses_module.py
  tests/mobly/base_instrumentation_test_test.py
  tests/mobly/base_test_test.py
  tests/mobly/controllers/android_device_lib/service_manager_test.py
  tests/mobly/utils_test.py
Labels: refactor

#725 Prefer monotonic time from perf_counter for time measurement.
  mobly/controllers/android_device.py
  mobly/controllers/android_device_lib/callback_handler.py
  mobly/controllers/android_device_lib/event_dispatcher.py
  mobly/controllers/android_device_lib/services/logcat.py
  mobly/controllers/android_device_lib/sl4a_client.py
  mobly/controllers/android_device_lib/snippet_client.py
  tests/mobly/controllers/android_device_test.py
Labels: refactor

#728 Remove 'future' compatibility layer dependency.
  setup.py
Labels: refactor
