Repository google/mobly, pull requests merged in 2021-05, with the labels that each got.

#740 Add support for `max_consecutive_error` in `repeat`.
  mobly/base_test.py
  tests/mobly/base_test_test.py
Labels: new feature

#743 Check Android devices exist before calling commands on them.
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement

#744 Fix a bug in `android_device.get_instances_with_configs`.
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: bug

#742 fix flake8 warning (#741)
  mobly/base_test.py
  mobly/controller_manager.py
  mobly/records.py
  mobly/suite_runner.py
  mobly/test_runner.py
  mobly/utils.py
Labels: refactor

#730 Add arg: filename for screenshot
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement

#746 Raise an error when `adb connect` fails.
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: bug

#747 Do not raise Error for already connected devices.
  mobly/controllers/android_device_lib/adb.py
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: improvement

#749 Supports `universal_newlines` as argument in utils#run_command
  mobly/utils.py
  tests/mobly/utils_test.py
Labels: improvement

#750 Use `self.assertIsInstance(..., ...)` instead of `self.assertTrue(isinstance(..., ...))`.
  tests/mobly/utils_test.py
Labels: testing

#751 Show test run metadata in test summary.
  mobly/logger.py
  mobly/test_runner.py
Labels: improvement, refactor
