Repository google/mobly, pull requests merged in 2021-03, with the labels that each got.

#731 Include a debug hint in snippet client error message.
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
Labels: improvement

#732 Fix the behavior of `SnippetClient#is_alive`.
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
  mobly/controllers/android_device_lib/services/snippet_management_service.py
  mobly/controllers/android_device_lib/snippet_client.py
  tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py
  tests/mobly/controllers/android_device_lib/services/snippet_management_service_test.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
Labels: bug

#733 Fix typo.
  mobly/utils.py
Labels: docs
