Repository google/mobly, pull requests merged in 2021-12, with the labels that each got.

#777 Use convenience constant instead hard code everywhere for MBS.
  docs/tutorial.md
Labels: docs

#775 Remove unused import in utils_test.py.
  tests/mobly/utils_test.py
Labels: refactor, testing

#776 Replace psutil usage with subprocess in utils.run_command.
  mobly/controllers/android_device_lib/adb.py
  mobly/utils.py
  tests/mobly/controllers/android_device_lib/adb_test.py
  tests/mobly/utils_test.py
Labels: refactor

#779 Add type hint to utils.run_command to fix pytype checker error.
  mobly/utils.py
  setup.py
Labels: bug

#780 Remove unreachable class method in AdbTest.
  tests/mobly/controllers/android_device_lib/adb_test.py
Labels: testing

#778 Create enum for build info constants
  mobly/controllers/android_device.py
Labels: refactor

#781 Fix bad import order according to Google Python style guide.
  tests/mobly/utils_test.py
Labels: refactor

#782 Refactor utils_test to follow Google Python style guide.
  tests/mobly/utils_test.py
Labels: testing

#783 Remove psutil usages in utils_test.
  tests/mobly/utils_test.py
Labels: testing

#785 Replace mock with unittest.mock and cleanup import section.
  tests/lib/integration2_test.py
  tests/lib/integration_test.py
  tests/lib/jsonrpc_client_test_base.py
  tests/lib/mock_android_device.py
  tests/lib/mock_instrumentation_test.py
  tests/lib/teardown_class_failure_test.py
  tests/lib/utils.py
  tests/mobly/base_instrumentation_test_test.py
  tests/mobly/base_test_test.py
  tests/mobly/controller_manager_test.py
  tests/mobly/controllers/android_device_lib/adb_test.py
  tests/mobly/controllers/android_device_lib/callback_handler_test.py
  tests/mobly/controllers/android_device_lib/errors_test.py
  tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py
  tests/mobly/controllers/android_device_lib/jsonrpc_shell_base_test.py
  tests/mobly/controllers/android_device_lib/service_manager_test.py
  tests/mobly/controllers/android_device_lib/services/base_service_test.py
  tests/mobly/controllers/android_device_lib/services/logcat_test.py
  tests/mobly/controllers/android_device_lib/services/sl4a_service_test.py
  tests/mobly/controllers/android_device_lib/services/snippet_management_service_test.py
  tests/mobly/controllers/android_device_lib/sl4a_client_test.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
  tests/mobly/controllers/android_device_lib/snippet_event_test.py
  tests/mobly/controllers/android_device_test.py
  tests/mobly/logger_test.py
  tests/mobly/output_test.py
  tests/mobly/records_test.py
  tests/mobly/suite_runner_test.py
  tests/mobly/test_runner_test.py
  tests/mobly/test_suite_test.py
  tests/mobly/utils_test.py
  tox.ini
Labels: testing

#786 Add a test case to cover kill subprocess and descendants behavior.
  tests/mobly/utils_test.py
Labels: testing

#787 Replace psutil usages in utils.stop_standing_subprocess.
  mobly/utils.py
  setup.py
  tests/mobly/utils_test.py
Labels: refactor

#766 Add basic `retry()` and `repeat()` support to generated tests.
  mobly/base_test.py
  tests/mobly/base_test_test.py
Labels: improvement

#788 Fix import order and disable broad-except pylint warning.
  mobly/utils.py
Labels: refactor

#789 Improve test coverage in Mobly utils.
  tests/mobly/utils_test.py
Labels: testing
