Repository google/mobly, pull requests merged in 2022-03, with the labels that each got.

#799 Mobly Release 1.11.1.
  CHANGELOG.md
  setup.cfg
  setup.py
Labels: release

#795 Add a new base class for snippet client
  mobly/snippet/__init__.py
  mobly/snippet/client_base.py
  mobly/snippet/errors.py
  tests/mobly/snippet/__init__.py
  tests/mobly/snippet/client_base_test.py
Labels: new feature

#801 Run yapf to fix format
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: refactor
