Repository google/mobly, pull requests merged in 2022-06, with the labels that each got.

#830 Fix typos in tutorial.md
  docs/tutorial.md
Labels: docs

#826 Standardize Async RPC for snippet client v2
  mobly/controllers/android_device_lib/callback_handler_v2.py
  mobly/controllers/android_device_lib/snippet_client_v2.py
  mobly/snippet/callback_event.py
  mobly/snippet/callback_handler_base.py
  mobly/snippet/errors.py
  tests/mobly/controllers/android_device_lib/callback_handler_v2_test.py
  tests/mobly/controllers/android_device_lib/snippet_client_v2_test.py
  tests/mobly/snippet/callback_event_test.py
  tests/mobly/snippet/callback_handler_base_test.py
Labels: refactor, improvement

#832 Alias error classes of callback handler v1 to the new ones
  mobly/controllers/android_device_lib/callback_handler.py
Labels: refactor

#834 ClientBase shouldn't call "stop" if "before_starting_server" failed
  mobly/snippet/client_base.py
  tests/mobly/snippet/client_base_test.py
Labels: bug

#836 Add error type to `ExceptionRecord`.
  mobly/records.py
  tests/mobly/records_test.py
Labels: improvement

#835 Support switching to client V2 via Android Device property setting
  mobly/controllers/android_device_lib/services/snippet_management_service.py
  tests/mobly/controllers/android_device_lib/services/snippet_management_service_test.py
Labels: improvement

#837 Add termination signal type to record.
  mobly/records.py
  tests/mobly/records_test.py
Labels: improvement

#838 Remove argv check. Check is already done in parse_cli_args.
  mobly/suite_runner.py
  tests/mobly/suite_runner_test.py
Labels: bug

#839 Flip the default Android snippet client version to V2
  mobly/controllers/android_device_lib/services/snippet_management_service.py
  tests/mobly/controllers/android_device_lib/services/snippet_management_service_test.py
  tests/mobly/controllers/android_device_test.py
Labels: refactor
