Repository google/mobly, pull requests merged in 2022-05, with the labels that each got.

#814 Remove the host_port and device_port attributes from ClientBase
  mobly/controllers/android_device_lib/snippet_client_v2.py
  mobly/snippet/client_base.py
Labels: refactor

#813 ClientBase should call "stop" if "before_starting_server" failed
  mobly/snippet/client_base.py
  tests/mobly/snippet/client_base_test.py
Labels: improvement

#808 Add Snippet Client V2 for Android, Step 2
  mobly/controllers/android_device_lib/snippet_client_v2.py
  tests/mobly/controllers/android_device_lib/snippet_client_v2_test.py
Labels: improvement

#819 Drop Python3.6 support. pytest removed Python 3.6 support so it is di…
  .github/workflows/ci.yml
  README.md
Labels: refactor

#815 Add a flag for whether to use Snippet Client V2
  mobly/controllers/android_device_lib/services/snippet_management_service.py
  tests/mobly/controllers/android_device_lib/services/snippet_management_service_test.py
Labels: improvement

#821 Fix the bug that event client is broken after reboot
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
  mobly/controllers/android_device_lib/snippet_client.py
  tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
Labels: bug

#824 Alias error classes of snippet client v1 to the new ones in snippet package
  mobly/controllers/android_device_lib/jsonrpc_client_base.py
  mobly/controllers/android_device_lib/snippet_client.py
Labels: refactor

#822 Event client clears host_port and device_port attribute
  mobly/controllers/android_device_lib/snippet_client.py
  tests/mobly/controllers/android_device_lib/snippet_client_test.py
Labels: bug

#823 Remove the dependency of client v2's unit test on subprocess
  tests/mobly/controllers/android_device_lib/snippet_client_v2_test.py
Labels: testing

#817 Create base suite class and add run_suite_class to suite runner.
  mobly/base_suite.py
  mobly/suite_runner.py
  tests/mobly/suite_runner_test.py
Labels: refactor, improvement

#810 Fix typo in run_command
  mobly/utils.py
  tests/mobly/utils_test.py
Labels: bug

#825 Client V2 cleans event client when it stops
  mobly/controllers/android_device_lib/snippet_client_v2.py
  tests/mobly/controllers/android_device_lib/snippet_client_v2_test.py
Labels: bug
