Repository google/mobly, pull requests merged in 2024-08, with the labels that each got.

#932 Add utils for installing and uninstalling apks.
  mobly/controllers/android_device_lib/apk_utils.py
  tests/mobly/controllers/android_device_lib/apk_utils_test.py
Labels: new feature

#933 Apply pyink formatting.
  tests/mobly/controllers/android_device_lib/snippet_client_v2_test.py
Labels: refactor

#934 Support passing stdout and stderr in start_standing_subprocess
  mobly/utils.py
  tests/mobly/utils_test.py
Labels: improvement

#937 Mobly Release 1.12.4
  CHANGELOG.md
  pyproject.toml
Labels: release

#938 Support selecting test cases in a class with regex
  mobly/base_suite.py
  mobly/base_test.py
  mobly/test_runner.py
  tests/mobly/base_test_test.py
Labels: new feature

#940 Update jetpack reference to `androidx`.
  mobly/base_instrumentation_test.py
Labels: docs
