Repository google/mobly, pull requests merged in 2024-01, with the labels that each got.

#906 Count should only count retries and not repeats.
  mobly/records.py
  tests/mobly/records_test.py
Labels: bug

#909 Bump min Python ver to 3.11.
  .github/workflows/ci.yml
  README.md
  mobly/utils.py
  setup.py
  tests/lib/mock_android_device.py
  tests/mobly/controllers/android_device_lib/snippet_client_v2_test.py
Labels: improvement

#910 Cache `AndroidDevice#model` to reduce fastboot calls
  mobly/controllers/android_device.py
  tests/mobly/controllers/android_device_test.py
Labels: improvement

#911 Switch to pyproject.toml completely
  mobly/utils.py
  pyproject.toml
  setup.cfg
  setup.py
Labels: refactor, improvement

#891 Fix whitespace stripping in _collect_process_tree
  mobly/utils.py
Labels: improvement
