Repository google/mobly, pull requests merged in 2025-03, with the labels that each got.

#956 Fix suite_runner.run_suite example in docs
  mobly/suite_runner.py
Labels: docs

#952 Add timeout support for FastbootProxy
  mobly/controllers/android_device_lib/fastboot.py
  tests/mobly/controllers/android_device_lib/fastboot_test.py
Labels: improvement

#958 Update docstring of AndroidDevice controller
  mobly/controllers/android_device.py
Labels: docs

#959 Set default timeout for fastboot command
  mobly/controllers/android_device_lib/fastboot.py
  tests/mobly/controllers/android_device_lib/fastboot_test.py
Labels: bug

#957 Check whether adb forwarding takes effect when hit socket connection failure
  mobly/controllers/android_device_lib/snippet_client_v2.py
  tests/mobly/controllers/android_device_lib/snippet_client_v2_test.py
Labels: improvement
